apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/akashdocker303/nihikernel-backend:devo-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GOOGLE_API_KEY
            - name: ALLOWED_ORIGINS
              value: "http://192.168.49.2:30080,http://localhost:3000,http://127.0.0.1:3000"
