apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: nihikernel-dev
data:
  ALLOWED_ORIGINS: "http://192.168.49.2:30080,http://localhost:3000,http://127.0.0.1:3000,http://16.16.208.171:3000,http://nihikernel.local,,http://16.16.208.171"
