apiVersion: v1
kind: PersistentVolume
metadata:
  name: nihikernel-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/nihikernel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nihikernel-pvc
  namespace: nihikernel-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi