
export const keywords = [
  'Abstraction',
  'Access Control List (ACL)',
  'Actor Model',
  'Ad Hoc Polymorphism',
  'Adjacency Matrix',
  'Adjacency List',
  'ADT (Abstract Data Type)',
  'AES (Advanced Encryption Standard)',
  'Affinity Propagation',
  'Agile',
  'Aho-Corasick Algorithm',
  'Algebraic Data Type',
  'Algorithm',
  'Alpha-Beta Pruning',
  'Analog Signal',
  'Angular',
  'Antivirus',
  'API ',
  'Application State',
  'ARM (Advanced RISC Machine)',
  'Array',
  'Array Stack',
  'Assembly Language',
  'Asynchronous Programming',
  'Atomic Operation',
  'Authentication',
  'Authorization',
  'Autonomic Computing',
  'Autoregressive Model',
  'AVL Tree',
  'Back-propagation',
  'Backtracking',
  'Backus-Naur Form (BNF)',
  'Balanced Binary Search Tree',
  'Bandwidth',
  'Barrier Synchronization',
  'Base64',
  'bash',
  'Behavioral Pattern',
  'Bellman-Ford Algorithm',
  'Big Data',
  'Big O Notation',
  'Binary Code',
  'Binary Search',
  'Binary Search Tree',
  'Binary Semaphore',
  'Binary Tree',
  'Biometric Authentication',
  'Bitmap',
  'Black-box Testing',
  'Blockchain',
  'Blocking',
  'Bloom Filter',
  'Bootloader',
  'Bouncing Pointers',
  'Boyer-Moore Algorithm',
  'Breadth-First Search (BFS)',
  'Breakpoint',
  'B-Tree',
  'B-Tree*',
  'Buffer Overflow',
  'Bug',
  'Build Automation',
  'Bus',
  'Busy Waiting',
  'Byte',
  'C (Programming Language)',
  'Cache',
  'Cache Coherence',
  'Cache Hit',
  'Cache Miss',
  'C++ (Programming Language)',
  'Calamity Theory',
  'Callback',
  'Canonical Huffman Tree',
  'Capacitor',
  'Captcha',
  'Cascading Style Sheets (CSS)',
  'Central Processing Unit (CPU)',
  'Chain of Responsibility Pattern',
  'Chaos Theory',
  'Character Encoding',
  'Chatbot',
  'Checkpointing',
  'Chomsky Hierarchy',
  'Circular Buffer',
  'Class',
  'Clustering',
  'Code Injection',
  'Code Obfuscation',
  'Cohesion',
  'Collection',
  'Compiler',
  'Complexity Theory',
  'Component-Based Development',
  'Composite Pattern',
  'Compression',
  'Computational Fluid Dynamics',
  'Computer Vision',
  'Concurrency',
  'Condition Variable',
  'Conjugate Gradient Method',
  'Constructor',
  'Continuous Integration (CI)',
  'Continuous Delivery (CD)',
  'Control Flow Graph',
  'CouchDB',
  'Coupling',
  'Crash',
  'Creational Pattern',
  'Cryptography',
  'CUDA (Compute Unified Device Architecture)',
  'Cyclic Redundancy Check (CRC)',
  'Dangling Pointer',
  'Database',
  'Database Migration',
  'Data Compression',
  'Dataflow Analysis',
  'Data Lake',
  'Data Mining',
  'Data Modeling',
  'Data Science',
  'Data Structure',
  'Data Type',
  'Deadlock',
  'Debug',
  'Debugger',
  'Decentralized Autonomous Organization (DAO)',
  'Deep Learning',
  'Default Method',
  'Defensive Programming',
  'Delegation Pattern',
  'Denormalization',
  'Depth-First Search (DFS)',
  'Dequeue',
  'Deserialization',
  'Design Pattern',
  'Destructor',
  'DevOps',
  'DHCP (Dynamic Host Configuration Protocol)',
  'DH Key Exchange (Diffie-Hellman)',
  'Dialogflow',
  'Digital Signal',
  'Dijkstra\'s Algorithm',
  'Directed Acyclic Graph (DAG)',
  'Distributed System',
  'Django',
  'DNS (Domain Name System)',
  'Docker',
  'Document-Oriented Database',
  'Double-Checked Locking',
  'Doubly Linked List',
  'Download',
  'Driver',
  'Dynamic Array',
  'Dynamic Programming',
  'Edge Computing',
  'Eigendecomposition',
  'Encapsulation',
  'Encryption',
  'Endianness',
  'Endpoint',
  'Enum',
  'ERM (Entity Relationship Model)',
  'Ethereum',
  'Event-Driven Architecture',
  'Evolutionary Algorithm',
  'Exception Handling',
  'Executor',
  'Expression Tree',
  'Facial Recognition',
  'Factory Pattern',
  'Fairness in Machine Learning',
  'Fault Tolerance',
  'FIFO (First-In, First-Out)',
  'File System',
  'Filter Pattern',
  'Firmware',
  'FizzBuzz',
  'Flask',
  'Floating Point Error',
  'Floyd-Warshall Algorithm',
  'Fork',
  'Fractal',
  'Framework',
  'FSM (Finite State Machine)',
  'Functional Programming',
  'Future',
  'Garbage Collection',
  'Gated Recurrent Unit (GRU)',
  'Gaussian Process',
  'Generative Adversarial Network (GAN)',
  'Genetic Algorithm',
  'Git',
  'Global Interpreter Lock (GIL)',
  'Google Cloud Platform (GCP)',
  'Google Search',
  'Graceful Degradation',
  'Gradient Descent',
  'Graph',
  'Graph Database',
  'Greedy Algorithm',
  'HAL (Hardware Abstraction Layer)',
  'Handler',
  'Hard Drive',
  'Hardening',
  'Hardware',
  'Hash Function',
  'Hash Table',
  'Heuristic',
  'Hexadecimal',
  'Hidden Markov Model',
  'Hierarchical Clustering',
  'High-Performance Computing',
  'Hook',
  'HTML (HyperText Markup Language)',
  'HTTP (Hypertext Transfer Protocol)',
  'Hub',
  'Huffman Coding',
  'Human-Computer Interaction (HCI)',
  'Hypervisor',
  'Idempotence',
  'Image Processing',
  'Immutable',
  'In-memory Database',
  'Indexed Sequential Access Method (ISAM)',
  'Induction',
  'Inference',
  'Infinite Loop',
  'Information Theory',
  'Inheritance',
  'Input/Output (I/O)',
  'Insertion Sort',
  'Instance',
  'Interpreter',
  'Inter-Process Communication (IPC)',
  'IP (Internet Protocol)',
  'Iterable',
  'JIT (Just-in-Time) Compilation',
  'Job Scheduler',
  'JSON (JavaScript Object Notation)',
  'Java',
  'JavaScript',
  'Jenkins',
  'Jinja',
  'Jupyter Notebook',
  'K-Means Clustering',
  'K-Nearest Neighbors (KNN)',
  'Kernel',
  'Key-Value Store',
  'Kruskal\'s Algorithm',
  'Kubernetes',
  'Lambda',
  'Latency',
  'Layered Architecture',
  'Least Recently Used (LRU) Cache',
  'Library',
  'LIFO (Last-In, First-Out)',
  'Linked List',
  'Liskov Substitution Principle (LSP)',
  'Liveness',
  'llm',
  'Load Balancer',
  'Local Area Network (LAN)',
  'Lock',
  'Lock-Free Algorithm',
  'Logging',
  'Login',
  'Long Short-Term Memory (LSTM)',
  'Loss Function',
  'Luhn Algorithm',
  'Machine Learning',
  'Macro',
  'Mainframe',
  'Managed Code',
  'MapReduce',
  'Markup Language',
  'Master-Slave Architecture',
  'Matrix',
  'Matrix Factorization',
  'Maven',
  'Max-Heap',
  'Memory',
  'Memory Leak',
  'Merge Sort',
  'Message Bus',
  'Message Queue',
  'Microkernel',
  'Microservice Architecture',
  'Min-Heap',
  'Modal Logic',
  'Model-View-Controller (MVC)',
  'MongoDB',
  'Monte Carlo Method',
  'Mutex (Mutual Exclusion)',
  'N-gram',
  'Natural Language Processing (NLP)',
  'Neural Network',
  'Nginx',
  'Node.js',
  'Non-Blocking I/O',
  'Non-Deterministic Finite Automaton (NFA)',
  'Normalization',
  'NoSQL',
  'Not-a-Number (NaN)',
  'Null Pointer',
  'Object-Oriented Programming (OOP)',
  'Observer Pattern',
  'Operating System',
  'Optimization',
  'Packet',
  'Packet Loss',
  'Parallel Computing',
  'Pass by Reference',
  'Pass by Value',
  'Password',
  'Pattern Recognition',
  'Permission',
  'Persistent Data',
  'Petri Net',
  'Pipe',
  'Pipelining',
  'Platform-as-a-Service (PaaS)',
  'Pointer',
  'Polling',
  'Polymorphism',
  'PostgreSQL',
  'Pragma',
  'Prim\'s Algorithm',
  'Prime Number',
  'Process',
  'Process Scheduling',
  'Producer-Consumer Problem',
  'Program Counter',
  'Protocol',
  'Proxy Server',
  'Public-Key Cryptography',
  'Python',
  'Queue',
  'Quicksort',
  'Race Condition',
  'Random Access Memory (RAM)',
  'Random Forest',
  'Randomized Algorithm',
  'Reactive Programming',
  'Read-Write Lock',
  'Real-Time Operating System (RTOS)',
  'Recursion',
  'Red-Black Tree',
  'Redis',
  'Register',
  'Relational Database',
  'Remote Procedure Call (RPC)',
  'Render',
  'Repository Pattern',
  'RESTful API',
  'Router',
  'RPC',
  'RSA Algorithm',
  'Ruby',
  'Rule Engine',
  'Run-Length Encoding',
  'Runtime',
  'Runtime Error',
  'Rust (Programming Language)',
  'SAN (Storage Area Network)',
  'Scaffolding',
  'Schema',
  'Scrum',
  'SDK (Software Development Kit)',
  'Search Engine',
  'Secure Sockets Layer (SSL)',
  'Security',
  'Segmentation Fault',
  'Semantics',
  'Semaphore',
  'Serialization',
  'Serverless Computing',
  'Session',
  'Shadowing',
  'Shell',
  'Shellshock',
  'Signal Processing',
  'Signed Integer',
  'Signed vs Unsigned',
  'Singleton Pattern',
  'Singly Linked List',
  'Site-to-Site VPN',
  'Sizing',
  'Sketching',
  'Sleep Sort',
  'Software-as-a-Service (SaaS)',
  'Software Development Life Cycle (SDLC)',
  'Software Engineering',
  'SOLID Principles',
  'Source Control',
  'Space Complexity',
  'Spanning Tree',
  'Spaghetti Code',
  'SQL (Structured Query Language)',
  'Stack',
  'State Machine',
  'Stateful',
  'Stateless',
  'Static Analysis',
  'Static Method',
  'Static Typing',
  'Stream Processing',
  'Structural Pattern',
  'Subnet',
  'Supervised Learning',
  'Support Vector Machine (SVM)',
  'Symmetric Cryptography',
  'Synchronous Programming',
  'Syntax',
  'Syntax Analysis',
  'System Call',
  'Systemd',
  'Tail Recursion',
  'TDD (Test-Driven Development)',
  'TCP (Transmission Control Protocol)',
  'Temporal Logic',
  'TensorFlow',
  'Terminator',
  'Thread',
  'Thrashing',
  'Time Complexity',
  'Time-of-Check to Time-of-Use (TOCTOU)',
  'Timeout',
  'Tokenizer',
  'Topology',
  'Tor',
  'Trie',
  'Tree',
  'Tree Traversal',
  'Trigonometry',
  'Tuple',
  'Turing Machine',
  'Two-Factor Authentication (2FA)',
  'UML (Unified Modeling Language)',
  'Unicast',
  'Unicode',
  'Unit Testing',
  'Unsupervised Learning',
  'URL (Uniform Resource Locator)',
  'User Authentication',
  'User Interface (UI)',
  'User Experience (UX)',
  'Userland',
  'Validation',
  'Value Type',
  'Variable',
  'Vector',
  'Virtual Machine',
  'Virtual Memory',
  'VLAN',
  'Vulnerability',
  'WAN (Wide Area Network)',
  'Web Server',
  'Web Socket',
  'WebAssembly',
  'WebSocket',
  'Webhook',
  'Wi-Fi',
  'Wildcard',
  'Workflow',
  'X.509 Certificate',
  'XML (eXtensible Markup Language)',
  'YAML',
  'Z-Buffer',
  'Zero-Day Exploit',
  'Zookeeper',
  'Zombified Process',
  '3-Way Handshake', 'Acceptance Testing', 'Access Modifier', 'Acyclic Graph',
  'Adapter Pattern', 'Address Resolution Protocol (ARP)', 'Ad-Hoc Network',
  'AJAX', 'Amazon Web Services (AWS)', 'And-Inverter Graph', 'Anisotropic Filtering',
  'Antialiasing', 'Apache HTTP Server', 'Application Lifecycle Management (ALM)',
  'Aspect-Oriented Programming (AOP)', 'Asset Pipeline', 'Asynchronous Request',
  'Azure', 'Balanced Parentheses', 'Bayesian Network', 'Binary Heap',
  'Bipartite Graph', 'Bitwise Operation', 'Boolean Logic', 'Bootstrap',
  'Bubble Sort', 'Builder Pattern', 'Bytecode', 'Call Stack', 'CamelCase',
  'Canonical Name', 'Capillary Electrophoresis', 'Chaining', 'Chunking',
  'Ciphertext', 'Circulant Matrix', 'Class Loader', 'Closure', 'Code Coverage',
  'Coexistence', 'Collada', 'Collatz Conjecture', 'Command Pattern',
  'Command-Line Interface (CLI)', 'Compaction', 'Completeness', 'Conditional Statement',
  'Configuration Management', 'Containerization', 'Cookie', 'Coroutine', 'CRDT',
  'Cross-Origin Resource Sharing (CORS)', 'Cross-Site Scripting (XSS)',
  'Cryptographic Hash Function', 'Cursor', 'Cyclic Dependency', 'Data Governance',
  'Data Normalization', 'Data Race', 'Data Warehouse', 'Datagram', 'Debouncing',
  'Decorator Pattern', 'Decoupling', 'Default Gateway', 'Denial-of-Service (DoS)',
  'Dependency Injection', 'Depth Buffer', 'Design by Contract', 'Dev-Sec-Ops',
  'Difference Engine', 'Digital Rights Management (DRM)', 'Directory Traversal',
  'Discrete Mathematics', 'Disk I/O', 'Distance Vector Routing Protocol', 'DNS Spoofing',
  'Domain-Driven Design (DDD)', 'Double-Entry Accounting', 'Downcasting',
  'Dry Principle', 'Duck Typing', 'Eager Loading', 'EBS', 'Echo Protocol',
  'EditorConfig', 'Efficient Frontier', 'Elasticsearch', 'Email Spoofing',
  'Embedded System', 'Encapsulated PostScript', 'Endpoint Detection',
  'Entity Component System (ECS)', 'Erlang', 'ERP System', 'Error Handling',
  'Event Sourcing', 'Explicit Congestion Notification (ECN)', 'Faceted Search',
  'Failure Mode and Effects Analysis (FMEA)', 'Fast Fourier Transform (FFT)',
  'Feature Flag', 'Feedforward Neural Network', 'Field Programmable Gate Array (FPGA)',
  'Filesystem in Userspace (FUSE)', 'Firewall', 'First Normal Form',
  'Fission', 'Fork-Join Model', 'Freemarker', 'Fuzzy Logic', 'Gantt Chart',
  'Gateway', 'Genetic Programming', 'Geolocation API', 'Git Flow', 'Global State',
  'GnuPG', 'Gompertz Curve', 'GraphQL', 'Grid Computing', 'Gulp', 'H.264',
  'Half-Duplex', 'Hamming Code', 'Handshake Protocol', 'Hard Real-Time System',
  'Hash Collision', 'Hash Tree', 'Heroku', 'Hibernate', 'High-Availability (HA)',
  'Homomorphic Encryption', 'Hotspot', 'HTTP/2', 'Hybrid Cloud', 'Idempotent',
  'Index', 'Indirect Branch', 'Infix Notation', 'Information Architecture',
  'Inheritance Hierarchy', 'Initial Public Offering (IPO)', 'Inline Function',
  'Integration Testing', 'Interface', 'Interleaving', 'Internet of Things (IoT)',
  'Inversion of Control (IoC)', 'IPsec', 'IPv4', 'Isomorphism', 'Jackson',
  'Jinja2', 'Joomla', 'JPEG', 'K-d Tree', 'Kafka', 'Kanban', 'Kerberos',
  'Keylogger', 'Key-Value Database', 'L.A.M.P Stack', 'Lambda Architecture',
  'Lazy Evaluation', 'Least Significant Bit (LSB)', 'Levenstein Distance',
  'Linear Congruential Generator', 'Linear Regression', 'Lisp', 'LLVM',
  'Load Factor', 'Logfile', 'Logical Clock', 'Loop Invariant', 'Lua',
  'Mac Address', 'Machine Code', 'Machine Learning Operations (MLOps)',
  'Map', 'Master Boot Record (MBR)', 'Matlab', 'Mediation Layer', 'Memcached',
  'Message Digest', 'Meta-Object Protocol (MOP)', 'Metadata', 'Minimax Algorithm',
  'MIPS', 'Model-View-ViewModel (MVVM)', 'Modularity', 'Monte Carlo Simulation',
  'Multiplexing', 'Named Pipes', 'Namespace', 'Netcat', 'NetFlow', 'Neural Style Transfer',
  'Newtonian Physics', 'Nondeterministic Polynomial Time (NP)', 'Non-Fungible Token (NFT)',
  'Non-Uniform Memory Access (NUMA)', 'NuGet', 'OAuth', 'Object Relational Mapping (ORM)',
  'OpenCL', 'Open Graph Protocol', 'Open Source', 'Operating System Kernel',
  'Orthogonality', 'Packet Sniffer', 'Parallelism', 'Parser', 'Partitioning',
  'Peer-to-Peer (P2P)', 'Perl', 'Phishing', 'Pig Latin', 'Ping of Death',
  'Post-Order Traversal', 'Predictive Analysis', 'Pre-Order Traversal', 'Private Key',
  'Project Management', 'Promise', 'Proprietary Software', 'Proxy Pattern',
  'Public Key Infrastructure (PKI)', 'Pure Function', 'Pyramid', 'Q-Learning',
  'Quadratic Probing', 'Quorum', 'RAID', 'Reactive Manifesto', 'Reactive System',
  'Read-Only Memory (ROM)', 'Redux', 'Relay', 'Remote Desktop Protocol (RDP)',
  'Representational State Transfer (REST)', 'Resilience', 'Revolutions Per Minute (RPM)',
  'Ring Buffer', 'Robotics', 'Rollback', 'Round-Robin Scheduling', 'RPC',
  'Routing Table', 'SAML', 'Schema-on-Read', 'Schema-on-Write', 'Scrapy',
  'Secure Boot', 'Secured Shell (SSH)', 'Semantic Versioning', 'Server-Side Rendering (SSR)',
  'Service Mesh', 'Sharding', 'Shellcode', 'Signal-to-Noise Ratio (SNR)',
  'Simulated Annealing', 'Single Page Application (SPA)', 'Single Point of Failure',
  'Singleton', 'Sliding Window', 'Smart Contract', 'Sniffer', 'Soap',
  'Software Development Kit (SDK)', 'Soft Real-Time System', 'Spam', 'Spark',
  'Spectre Attack', 'Spooling', 'Spring Framework', 'Staging Environment',
  'Static Code Analysis', 'Steganography', 'Stream Cipher', 'Streaming',
  'Subversion', 'Supercomputer', 'Swagger', 'Swarm Intelligence', 'Swift',
  'Symantec', 'Synchronous', 'Synthetic Data', 'System Design', 'T-SQL',
  'Tablet', 'Tarball', 'Telepresence', 'Telnet', 'Test Coverage', 'Test Double',
  'Test Harness', 'Throttling', 'Thunk', 'Timestamp', 'Token', 'Topology',
  'Trade-off Analysis', 'Transistor', 'Transpiler', 'Tritium', 'Trivial File Transfer Protocol (TFTP)',
  'Trojan Horse', 'Tunneling', 'Uncaught Exception', 'Uniform Resource Name (URN)',
  'Unwind', 'User Datagram Protocol (UDP)', 'Variable Scoping', 'Vector Graphics',
  'Vim', 'Virtual Private Cloud (VPC)', 'Virtualization', 'V-Model',
  'Voxel', 'Web Content Accessibility Guidelines (WCAG)', 'Web Scraping',
  'Weighted Directed Graph', 'White-Box Testing', 'Wired Equivalent Privacy (WEP)',
  'Wireless Fidelity (Wi-Fi)', 'Wrapper', 'Write-Back Cache', 'Write-Through Cache',
  'X.500', 'XPath', 'XSLT', 'Z-order Curve', 'Zero Knowledge Proof (ZKP)',
  'Zeta-function', 'Zone Transfer', 'ZooKeeper'
];